[CountriesWindow]
special_use_index = 1
deleted_index = 0

[CountriesWindow.geometry]
x = 4
y = 24
width = 1600
height = 749

[CountriesWindow.column_widths]
0 = 63
1 = 96
2 = 156
3 = 233
4 = 87
5 = 81
6 = 77
7 = 78
8 = 89
9 = 91
10 = 95
11 = 74
